# Generated by Django 3.0.5 on 2020-05-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_questionscores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='text',
        ),
        migrations.AddField(
            model_name='slide',
            name='fk',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
