# Generated by Django 3.0.5 on 2020-05-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200504_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='slide_number',
            new_name='choice_number',
        ),
        migrations.AlterOrderWithRespectTo(
            name='questionslide',
            order_with_respect_to='slide_number',
        ),
    ]
