# Generated by Django 3.0.5 on 2020-05-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200504_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['?']},
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='type',
            field=models.CharField(choices=[('S', 'Sequential'), ('B', 'Board')], default='N', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.TextField(choices=[('N', 'Normal'), ('C', 'MCQ'), ('O', 'Ordering')], max_length=1),
        ),
        migrations.DeleteModel(
            name='QuestionTypes',
        ),
    ]
