# Generated by Django 3.0.5 on 2020-05-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200504_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['choice_number']},
        ),
        migrations.AddField(
            model_name='question',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.TextField(choices=[('N', 'Normal'), ('C', 'MCQ'), ('O', 'Order')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questionscores',
            name='score',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='Untitled Quiz', max_length=64),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='secret',
            field=models.CharField(default='', max_length=32),
        ),
    ]
