# Generated by Django 3.0.5 on 2020-05-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200505_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterOrderWithRespectTo(
            name='round',
            order_with_respect_to='round_number',
        ),
    ]
