# Generated by Django 3.0.6 on 2020-05-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200505_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
    ]
