# Generated by Django 3.0.6 on 2020-05-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200506_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='name',
            field=models.CharField(default='Untitled Round', max_length=64),
        ),
    ]
